### ISSUE TITLE
anyone can help me

### ISSUE THREAD

**Issue by codesourse** [kishikawakatsumi/UICKeyChainStore#104]
UICKeyChainStore *keychain = [UICKeyChainStore keyChainStoreWithService:@"xh.english.brush"
                                                                        accessGroup:@"test.hello"];
    
            keychain[@"user_name"]    = loginView.userNameField.text;
            keychain[@"pass_word"]    = @"123456";
            keychain[@"downDataFlag"] = [returnValue.D ObjectForKey:@"downDataFlag"];
            keychain[@"usFlag"]       = [returnValue.D ObjectForKey:@"usFlag"];
            keychain[@"usGroupid"]    = [returnValue.D ObjectForKey:@"usGroupid"];
            keychain[@"usId"]         = [returnValue.D ObjectForKey:@"usId"];
            keychain[@"usName"]       = [returnValue.D ObjectForKey:@"usName"];
            keychain[@"usSessionId"]  = [returnValue.D ObjectForKey:@"usSessionId"];
            keychain[@"usType"]       = [returnValue.D ObjectForKey:@"usType"];
            keychain[@"usUid"]        = [returnValue.D ObjectForKey:@"usUid"];
            
            NSLog(@"keychainpass_word=%@",keychain[@"pass_word"]);

keychainpass_word is nil

**Comment by kishikawakatsumi** [comment]
It seems really weird. Other values, like"user_name", "downDataFlag", are stored correctly? Are there any error messages in Xcode console?

**Comment by codesourse** [comment]
UICKeyChainStore *keychain = [[UICKeyChainStore alloc]initWithService:@"xh.english.brush" accessGroup:@"hello"];
            keychain[@"pass_word"]    = @"21e12e";
            NSLog(@"keychainpass_word=%@",keychain[@"pass_word"]);


----------------------方法: __31-[LoginViewController loginAct]_block_invoke279 
----------------------行数: 153---------------------
----------------------内容:keychainpass_word=(null)

**Comment by kishikawakatsumi** [comment]
Could you please share reproducible project?

**Comment by codesourse** [comment]
you wait a minute,I create a new project.

**Comment by codesourse** [comment]
2015-08-08 15:56:32.345 testKeyChain[2374:281142] OSStatus error: [-25243] Security error has occurred.
2015-08-08 15:56:32.348 testKeyChain[2374:281142] keychainpass_word=(null)

**Comment by codesourse** [comment]
project:  https://github.com/codesourse/testKeyChain.git

**Comment by codesourse** [comment]
handsome boy help me.

**Comment by kishikawakatsumi** [comment]
@codesourse There is no code using UICKeyChainStore in the project. Did you forgot to commit your code?

**Comment by codesourse** [comment]
sorry,i commit it again.

**Comment by kishikawakatsumi** [comment]
Because you specify access group, you should make entitlements for allowing to access the access group. To make entitlements, 
1. Select project settings, then click capability tab
2. Turn ON Keychain Sharing
3. Input access group name that you use in your app (your example is 'hello')

<img width="1137" alt="screen shot 2015-08-10 at 23 13 03" src="https://cloud.githubusercontent.com/assets/40610/9173517/ab309a80-3fb5-11e5-9047-9445f82acfb0.png">

Then, the entitlements file will be like following:

<img width="933" alt="screen shot 2015-08-10 at 23 17 15" src="https://cloud.githubusercontent.com/assets/40610/9173562/fcee75e0-3fb5-11e5-86a1-7f3f1ca9f710.png">

You should specify access group with "App ID prefix". So the code is to be like following:
(`27AEDK3C9F` is my App ID prefix. You have different one.)

```
UICKeyChainStore *keychain = [[UICKeyChainStore alloc]initWithService:@"xh.english.brush"
                                                              accessGroup:@"27AEDK3C9F.hello"];
```

**Comment by codesourse** [comment]
Why  it is ok,when running on the simulators?

**Comment by kishikawakatsumi** [comment]
Any simulators do not have access group. When running on simulators, the access group automatically set to `test` despite of you specifying any other text. So most keychain library ignore access group settings when running on simulators. Of course this library also does so.

**Comment by codesourse** [comment]
Thank you very much!
