### ISSUE TITLE
-dataForKey:error: doesn't set error if SecItemCopyMatching status is -25300 (errSecItemNotFound)

### ISSUE THREAD

**Issue by corristo** [kishikawakatsumi/UICKeyChainStore#108]
Here's why:
https://github.com/kishikawakatsumi/UICKeyChainStore/blob/afc33f49c3483f5b4526b244e39b1ebe5c4595d5/Lib/UICKeyChainStore/UICKeyChainStore.m#L471

Is it intentional? If not, I'd be happy to provide pull request with a fix.

**Comment by kishikawakatsumi** [comment]
Yes, it is intentional behaviour. This library treats any errors as programmer's error (e.g. wrong code signing entitlements, authentication failed, etc.) or unexpected system error (e.g. failed to allocate memory, security daemon is down, etc.). `errSecItemNotFound` is not an error. It indicates there is no any error, but cannot find matching key. I think it's practical for most cases.

**Comment by corristo** [comment]
@kishikawakatsumi thanks for explanation! Definitely makes sense.
