### ISSUE TITLE
How clear it when softwore have uninstalled

### ISSUE THREAD

**Issue by BulletTrain** [kishikawakatsumi/UICKeyChainStore#122]

**Comment by kishikawakatsumi** [comment]
You cannot it automatically. Because we have no any trigger the app uninstalling.

Things like similar can be achieved by combining the value disappear uninstall such as NSUserDefaults.

For example, you can generate key value when app launching, then store the value to NSUserDefaults. You always to use the value to store keychain as a key.
If app will be uninstalled, the key will be also removed. So you cannot retrieve the value when app installed again.
